//! Canonical Markdown rendering for the reviewed registry document.

use std::fmt::Write as _;

use super::{RegistryDocument, RegistryInvariant};
use support::{
    count_by, kind_label, render_count_table, render_evidence_references, render_family_map,
    sorted_invariants, FAMILY_ORDER,
};

mod support;

/// Renders the canonical Markdown view of a strictly parsed registry.
#[must_use]
pub fn render_registry_markdown(registry: &RegistryDocument) -> String {
    let mut output = String::new();
    render_header(&mut output, registry);
    render_policy(&mut output, registry);
    render_indexes(&mut output, registry);
    render_catalog(&mut output, registry);
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn render_header(output: &mut String, registry: &RegistryDocument) {
    let _ = writeln!(
        output,
        "<!-- Generated by scripts/render-raft-invariants-doc from verification/raft-invariants.yaml. -->\n"
    );
    let _ = writeln!(output, "# Raft Invariant Catalog\n");
    output.push_str(
        "This is Rafter's verification contract for one Raft group. It names the\n\
properties the implementation is expected to preserve, where evidence\n\
exists today, and what work would turn partial coverage into a direct\n\
oracle. It is not a claim that Raft has one universal finite invariant\n\
count; the count is meaningful because this registry fixes the scope and\n\
the row granularity.\n\n",
    );
    let _ = writeln!(output, "Repository: `{}`\n", registry.repository);
    let _ = writeln!(
        output,
        "Catalog origin ref: `{}`\n",
        registry.catalog_origin_ref
    );
    let _ = writeln!(
        output,
        "Catalog working ref (non-authoritative): `{}`\n",
        registry.catalog_working_ref
    );
    let _ = writeln!(output, "Audit date: `{}`\n", registry.audit_date);
    output.push_str("Generated from `verification/raft-invariants.yaml`; run `python3 scripts/render-raft-invariants-doc` after editing the registry and `python3 scripts/render-raft-invariants-doc --check` in CI.\n\n");
}

fn render_policy(output: &mut String, registry: &RegistryDocument) {
    let kind_counts = count_by(registry.invariants.iter().map(|entry| entry.kind.as_str()));
    output.push_str("## What This Counts\n\n");
    render_count_table(output, &registry.counts);
    let _ = writeln!(
        output,
        "\nThe catalog currently contains {} well-formedness row, {} safety rows, and {} liveness rows.\n",
        kind_counts.get("well_formedness").copied().unwrap_or_default(),
        kind_counts.get("safety").copied().unwrap_or_default(),
        kind_counts.get("liveness").copied().unwrap_or_default()
    );
    output.push_str(
        "Out of scope: transport encryption, peer authentication, application\n\
snapshot semantics, removed-peer authorization at the deployment boundary,\n\
application state durability above the runtime contract, and multi-group\n\
scheduling properties that are not per-group Raft consensus properties.\n\n",
    );
    output.push_str(
        "## Evidence Policy\n\n\
- Every safety invariant should have at least one direct executable oracle.\n\
- Every canonical safety invariant should have two independent evidence layers.\n\
- Every simulator checker should have a negative fixture proving it can fail.\n\
- Every client-visible invariant should have an end-to-end workload.\n\
- Every persistence invariant should have failure-injection or crash/reopen coverage.\n\
- Every liveness obligation should state its fairness and timing assumptions.\n\
- TLA+ `CompactSnapshot` retains a ghost logical log for safety witnesses; it is not physical compaction evidence. Simulator and storage tests own retained-prefix, offset, and crash/reopen compaction behavior.\n\
- Registered direct tests are total deterministic oracles: one exact exit-0 pass is green, zero execution is incomplete, and one canonical exact-test exit-101 failure is an invariant violation. Malformed, duplicate, timed-out, signaled, wrong-name, or other process failures are harness errors.\n\n\
## Layer Legend\n\n\
- D: direct executable oracle.\n\
- E2E: client-visible end-to-end consequence.\n\
- none: not covered, or not the right layer for that predicate.\n\n",
    );
}

fn render_indexes(output: &mut String, registry: &RegistryDocument) {
    output.push_str("## Family Map\n\n");
    render_family_map(output, &registry.invariants);
    output.push_str("\n## List\n\n");
    output.push_str("| ID | One-line description |\n| --- | --- |\n");
    for entry in sorted_invariants(&registry.invariants) {
        let _ = writeln!(output, "| `{}` | {} |", entry.id, entry.statement);
    }

    output.push_str("\n## First Closures\n\n");
    output.push_str(
        "These are the first closures because they turn broad green checks into\n\
named temporal or witness-based verdicts.\n\n\
| ID | Class | Work |\n\
| --- | --- | --- |\n",
    );
    for entry in sorted_invariants(&registry.invariants)
        .into_iter()
        .filter(|entry| entry.priority == "p0")
    {
        let _ = writeln!(
            output,
            "| `{}` | {} | {} |",
            entry.id, entry.action_class, entry.next_action
        );
    }

    output.push_str("\n## Evidence References\n\n");
    render_evidence_references(output, &registry.evidence);
    output.push_str("\n## Normative Clauses\n\n");
    output.push_str("| Clause | Parent | Normative statement |\n| --- | --- | --- |\n");
    for clause in &registry.clauses {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} |",
            clause.id, clause.invariant_id, clause.statement
        );
    }
}

fn render_catalog(output: &mut String, registry: &RegistryDocument) {
    output.push_str("\n## Catalog\n\n");
    for (family, label, _) in FAMILY_ORDER {
        let _ = writeln!(output, "### {label}\n");
        for entry in sorted_invariants(&registry.invariants)
            .into_iter()
            .filter(|entry| entry.family == *family)
        {
            render_invariant(output, registry, entry);
        }
    }
}

fn render_invariant(output: &mut String, registry: &RegistryDocument, entry: &RegistryInvariant) {
    let _ = writeln!(output, "#### `{}` {}\n", entry.id, entry.title);
    let _ = writeln!(
        output,
        "Kind: {}. Tier: {}.\n",
        kind_label(&entry.kind),
        entry.tier
    );
    let _ = writeln!(output, "Statement: {}\n", entry.statement);
    let _ = writeln!(output, "Scope: {}\n", entry.scope);
    let _ = writeln!(output, "Assumptions: {}\n", entry.assumptions);
    output.push_str("Required clauses:\n");
    for clause in registry
        .clauses
        .iter()
        .filter(|clause| clause.invariant_id == entry.id)
    {
        let _ = writeln!(output, "- `{}`: {}", clause.id, clause.statement);
    }
    output.push_str("\nEvidence now:\n");
    for (label, layer) in [
        ("TLA+", "tla"),
        ("Simulator", "simulator"),
        ("Tests", "tests"),
        ("Maelstrom", "maelstrom"),
    ] {
        let _ = writeln!(
            output,
            "- {label}: {}",
            entry.current_coverage.get(layer).map_or("", String::as_str)
        );
    }
    let _ = writeln!(
        output,
        "\nNext ({}): {}\n",
        entry.action_class, entry.next_action
    );
}

#[cfg(test)]
#[path = "render/tests.rs"]
mod tests;
