[workspace]
members = [
    "crates/rafter",
    "crates/rafter-codec",
    "crates/rafter-crc32",
    "crates/rafter-runtime-api",
    "crates/rafter-app",
    "crates/rafter-service",
    "crates/rafter-multiraft",
    "crates/rafter-runtime",
    "crates/rafter-invariant-test",
    "crates/rafter-invariants",
    "crates/rafter-sim",
    "crates/rafter-storage",
    "crates/rafter-maelstrom",
    "crates/rafter-transport-tcp-insecure",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/zsumz/rafter"
rust-version = "1.88"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
