//! Stable observation keys, complete state capture, and a compact reading transcript.

use std::fmt::Write;

use super::support::*;
use crate::node::state::{LeaderState, PersistentState, VolatileState};

fn state(node: &Node, text: &mut String) {
    // Exhaustive destructuring makes an added state field a conscious capture
    // decision. Schema keys name facts rather than Rust ownership groups. No
    // sorting, hashing, cursor substitution, or output normalization is used.
    let Node {
        config,
        persistent,
        volatile,
        election,
        leader,
        derived,
    } = node;
    let PersistentState {
        current_term,
        voted_for,
        committed_configuration,
        snapshot,
        log,
    } = persistent;
    let VolatileState {
        role,
        commit_index,
        dispatched_index: dispatch,
        local_proposals,
        incoming_snapshot,
        leader_hint,
        snapshot_chunk_rejections,
    } = volatile;
    let LeaderState {
        progress,
        ticks,
        lease,
        pending_transfer,
        deposition_authorized,
        heartbeat_sequence,
        heartbeat_elapsed,
        quorum_acks,
        quorum_check_elapsed,
        pending_reads,
    } = leader;
    for (key, value) in [
        ("configuration", format!("{config:?}")),
        ("term", format!("{current_term:?}")),
        ("vote", format!("{voted_for:?}")),
        (
            "committed-configuration",
            format!("{committed_configuration:?}"),
        ),
        ("snapshot", format!("{snapshot:?}")),
        ("log", format!("{log:?}")),
        ("role", format!("{role:?}")),
        ("commit", format!("{commit_index:?}")),
        ("dispatch", format!("{dispatch:?}")),
        ("local-proposals", format!("{local_proposals:?}")),
        ("incoming-snapshot", format!("{incoming_snapshot:?}")),
        ("leader-hint", format!("{leader_hint:?}")),
        (
            "snapshot-rejections",
            format!("{snapshot_chunk_rejections:?}"),
        ),
        ("election", format!("{election:?}")),
        ("replication-progress", format!("{progress:?}")),
        ("leader-ticks", format!("{ticks:?}")),
        ("lease", format!("{lease:?}")),
        ("transfer", format!("{pending_transfer:?}")),
        (
            "deposition-authorized",
            format!("{deposition_authorized:?}"),
        ),
        ("heartbeat-sequence", format!("{heartbeat_sequence:?}")),
        ("heartbeat-elapsed", format!("{heartbeat_elapsed:?}")),
        ("quorum-acks", format!("{quorum_acks:?}")),
        ("quorum-elapsed", format!("{quorum_check_elapsed:?}")),
        ("pending-reads", format!("{pending_reads:?}")),
        ("derived-indexes", format!("{derived:?}")),
    ] {
        writeln!(text, "{key}={value}").unwrap();
    }
}

pub(super) fn replay(scenarios: Vec<Scenario>) -> (String, String) {
    let mut observations = String::from("rafter-protocol-observations-v1\nbase=2a58d6e3\n");
    let mut document = String::from(
        "# Production-core walkthroughs\n\n\
         These observations are generated by `node::tests::walkthroughs` using the\n\
         actual `Node::step` and `Node::step_batch`. Default pre-vote and check-quorum\n\
         remain enabled; lease reads retain their default disabled setting.\n\n\
         **Raw-core boundary:** returning an output neither persists Raft state nor\n\
         executes application code. The embedding must persist dependent state before\n\
         releasing sends, read grants, or application effects, in the returned order.\n\
         `dispatch` includes no-ops, configurations, and the declared recovery floor.\n\
         It does not establish application execution or its durability.\n\n\
         The tables abbreviate outputs for reading. The [baseline observations](\n\
         src/node/tests/walkthroughs/observations.txt) retain every output, input,\n\
         and state field, including replication windows, pending reads, vote grants,\n\
         and derived indexes. Single-input observations include every tick; tables\n\
         group consecutive ticks at the named checkpoint. Batch boundaries are\n\
         explicit and are compared against their own pre-refactor baseline.\n\n",
    );
    for scenario in scenarios {
        writeln!(
            document,
            "## {}\n\n{}\n",
            scenario.name, scenario.explanation
        )
        .unwrap();
        writeln!(
            document,
            "Initial term={}, vote={:?}, commit={}, dispatch={}, last={} / term {}; membership={:?}.\n",
            scenario.node.current_term().0,
            scenario.node.voted_for(),
            scenario.node.commit_index().0,
            scenario.node.dispatched_index().0,
            scenario.node.last_log_index().0,
            scenario.node.last_log_term().0,
            scenario.node.effective_membership()
        )
        .unwrap();
        for batch in [false, true] {
            let mut node = scenario.node.clone();
            writeln!(observations, "scenario={}; batch={batch}", scenario.name).unwrap();
            state(&node, &mut observations);
            writeln!(document, "### {}\n\n| Input checkpoint | Inputs in order | Term / role / vote | Commit / dispatch / last | Pending reads | Ordered outputs |\n| --- | --- | --- | --- | --- | --- |",
                if batch { "Batched inputs" } else { "Single inputs" }).unwrap();
            for (label, inputs) in &scenario.steps {
                writeln!(observations, "checkpoint={label}").unwrap();
                let mut effects = Vec::new();
                let frames = if batch {
                    vec![inputs.clone()]
                } else {
                    inputs.iter().cloned().map(|input| vec![input]).collect()
                };
                for frame in frames {
                    writeln!(observations, "inputs={frame:?}").unwrap();
                    let outputs = if batch {
                        node.step_batch(frame)
                    } else {
                        node.step(frame.into_iter().next().unwrap())
                    };
                    writeln!(observations, "outputs={outputs:?}").unwrap();
                    assert_eq!(node.applied_index(), node.dispatched_index());
                    state(&node, &mut observations);
                    effects.extend(outputs);
                }
                let labels = effects.iter().map(effect).collect::<Vec<_>>().join("; ");
                let input_labels = inputs.iter().map(input).collect::<Vec<_>>().join("; ");
                writeln!(
                    document,
                    "| {label} | {input_labels} | {} / {:?} / {:?} | {} / {} / {} | {} | {} |",
                    node.current_term().0,
                    node.role(),
                    node.voted_for(),
                    node.commit_index().0,
                    node.dispatched_index().0,
                    node.last_log_index().0,
                    node.pending_read_count(),
                    if labels.is_empty() { "none" } else { &labels }
                )
                .unwrap();
            }
            writeln!(document).unwrap();
            assert_eq!(
                (
                    node.current_term(),
                    node.role(),
                    node.commit_index(),
                    node.last_log_index(),
                    node.pending_read_count()
                ),
                scenario.expected,
                "{} batch={batch}",
                scenario.name
            );
        }
    }
    document.truncate(document.trim_end().len());
    document.push('\n');
    (observations, document)
}

fn effect(output: &Output) -> String {
    match output {
        Output::Apply { index, .. } => format!("Apply({})", index.0),
        Output::ConfigurationCommitted { index, .. } => {
            format!("ConfigurationCommitted({})", index.0)
        }
        Output::Send { to, message } => match message {
            Message::AppendEntries(append) => format!(
                "Append to {}: prev={}, entries={}, commit={}, seq={}",
                to.0,
                append.prev_log_index.0,
                append.entries.len(),
                append.leader_commit.0,
                append.sequence
            ),
            _ => format!("Send to {}: {message:?}", to.0),
        },
        _ => format!("{output:?}"),
    }
}

fn input(input: &Input) -> String {
    match input {
        Input::Message { from, message } => match message {
            Message::AppendEntries(append) => format!(
                "Append from {}: term={}, prev={} / term {}, entry terms={:?}, leader_commit={}, seq={}",
                from.0, append.term.0, append.prev_log_index.0, append.prev_log_term.0,
                append.entries.iter().map(|entry| entry.term.0).collect::<Vec<_>>(),
                append.leader_commit.0, append.sequence,
            ),
            _ => format!("From {}: {message:?}", from.0),
        },
        _ => format!("{input:?}"),
    }
}
