[package]
name = "rafter-multiraft"
version = "0.0.1"
description = "Many-group host layer for Rafter."
readme = "README.md"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rafter-app = { path = "../rafter-app", version = "0.0.1" }
rafter-runtime-api = { path = "../rafter-runtime-api", version = "0.0.1" }

[dev-dependencies]
rafter = { path = "../rafter", version = "0.0.1" }
rafter-runtime = { path = "../rafter-runtime", version = "0.0.1" }
rafter-storage = { path = "../rafter-storage", version = "0.0.1" }

[lints]
workspace = true
