//! Field vocabulary and unknown-field rejection for registry records.

pub(super) fn section_fields(section: &str) -> &'static [&'static str] {
    match section {
        "invariants:" => &[
            "kind",
            "family",
            "tier",
            "priority",
            "title",
            "statement",
            "scope",
            "assumptions",
            "action_class",
            "next_action",
        ],
        "clauses:" => &[
            "invariant_id",
            "statement",
            "scope",
            "assumptions",
            "required",
        ],
        "evidence:" => &[
            "clauses",
            "layer",
            "strength",
            "path",
            "symbol",
            "persistence_evidence",
            "atomic_group",
            "package",
            "target_kind",
            "target",
            "test_name",
            "simulator_check",
            "minimum_protocol_states",
            "minimum_verifier_states",
            "minimum_runs_per_check",
            "minimum_steps",
            "required_observation",
            "minimum_observation",
            "negative_fixture",
            "negative_fixture_path",
            "negative_fixture_detector",
            "negative_fixture_detector_path",
            "negative_fixture_detector_bridge",
            "negative_fixture_uncovered",
            "negative_fixture_package",
            "negative_fixture_target_kind",
            "negative_fixture_target",
            "negative_fixture_test_name",
            "negative_fixture_exemption",
            "required_liveness_invariant",
            "required_liveness_clauses",
            "required_liveness_feature",
            "required_liveness_scenario",
            "liveness_fault_requirement",
            "liveness_stable_leader_retained",
            "liveness_stable_leader_rounds_minimum",
            "liveness_stable_leader_rounds_exact",
            "liveness_stable_leader_rounds_relation",
            "liveness_proposal_outcome",
            "liveness_authority_loss_required",
            "liveness_fault_cycle_required",
            "liveness_fairness_policy",
            "liveness_tick_bound_rounds",
            "liveness_delivery_bound_rounds",
            "liveness_max_delivery_waves_per_tick",
            "liveness_round_budget_provenance",
            "liveness_minimum_rounds",
            "liveness_rounds_per_node",
            "liveness_rounds_per_queued_message",
            "liveness_rounds_per_proposal",
            "liveness_rounds_per_membership_change",
            "liveness_rounds_per_partition",
            "liveness_snapshot_catchup_rounds",
            "liveness_phase_count",
            "liveness_fixed_rounds",
        ],
        _ => &[],
    }
}

pub(super) fn nested_fields(section: &str, field: &str) -> Option<&'static [&'static str]> {
    match (section, field) {
        ("invariants:", "current_coverage") => Some(&["tla", "simulator", "tests", "maelstrom"]),
        _ => None,
    }
}
