use std::{collections::BTreeMap, fmt::Write as _};

use crate::registry::{RegistryCounts, RegistryDocument, RegistryEvidence, RegistryInvariant};

const FAMILY_ORDER: &[(&str, &str, &str)] = &[
    (
        "state",
        "State Shape",
        "well-formed protocol state and derived indexes",
    ),
    (
        "election",
        "Terms, Votes, and Leadership",
        "terms, votes, leadership, pre-vote, and authority fencing",
    ),
    (
        "log",
        "Log Replication",
        "leader append-only behavior, append acceptance, and log matching",
    ),
    (
        "commit",
        "Commitment and Application",
        "commitment, application order, and state-machine safety",
    ),
    (
        "membership",
        "Dynamic Membership",
        "stable and joint configurations, learners, and transfers",
    ),
    (
        "read",
        "Read Barriers and Leases",
        "ReadIndex, lease reads, apply-before-read, and history checks",
    ),
    (
        "persistence",
        "Persistence, Restart, and Snapshots",
        "durability, restart, applied floors, and snapshots",
    ),
    (
        "liveness",
        "Liveness Obligations",
        "bounded progress obligations with explicit assumptions",
    ),
];

const PREFIX_ORDER: &[&str] = &["ST", "EL", "LG", "CM", "AP", "MB", "RD", "PS", "SS", "LV"];

/// Renders the canonical Markdown view of a strictly parsed registry.
#[must_use]
pub fn render_registry_markdown(registry: &RegistryDocument) -> String {
    let mut output = String::new();
    render_header(&mut output, registry);
    render_policy(&mut output, registry);
    render_indexes(&mut output, registry);
    render_catalog(&mut output, registry);
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn render_header(output: &mut String, registry: &RegistryDocument) {
    let _ = writeln!(
        output,
        "<!-- Generated by scripts/render-raft-invariants-doc from verification/raft-invariants.yaml. -->\n"
    );
    let _ = writeln!(output, "# Raft Invariant Catalog\n");
    output.push_str(
        "This is Rafter's verification contract for one Raft group. It names the\n\
properties the implementation is expected to preserve, where evidence\n\
exists today, and what work would turn partial coverage into a direct\n\
oracle. It is not a claim that Raft has one universal finite invariant\n\
count; the count is meaningful because this registry fixes the scope and\n\
the row granularity.\n\n",
    );
    let _ = writeln!(output, "Repository: `{}`\n", registry.repository);
    let _ = writeln!(
        output,
        "Catalog origin ref: `{}`\n",
        registry.catalog_origin_ref
    );
    let _ = writeln!(
        output,
        "Catalog working ref (non-authoritative): `{}`\n",
        registry.catalog_working_ref
    );
    let _ = writeln!(output, "Audit date: `{}`\n", registry.audit_date);
    output.push_str("Generated from `verification/raft-invariants.yaml`; run `python3 scripts/render-raft-invariants-doc` after editing the registry and `python3 scripts/render-raft-invariants-doc --check` in CI.\n\n");
}

fn render_policy(output: &mut String, registry: &RegistryDocument) {
    let kind_counts = count_by(registry.invariants.iter().map(|entry| entry.kind.as_str()));
    output.push_str("## What This Counts\n\n");
    render_count_table(output, &registry.counts);
    let _ = writeln!(
        output,
        "\nThe catalog currently contains {} well-formedness row, {} safety rows, and {} liveness rows.\n",
        kind_counts.get("well_formedness").copied().unwrap_or_default(),
        kind_counts.get("safety").copied().unwrap_or_default(),
        kind_counts.get("liveness").copied().unwrap_or_default()
    );
    output.push_str(
        "Out of scope: transport encryption, peer authentication, application\n\
snapshot semantics, removed-peer authorization at the deployment boundary,\n\
application state durability above the runtime contract, and multi-group\n\
scheduling properties that are not per-group Raft consensus properties.\n\n",
    );
    output.push_str(
        "## Evidence Policy\n\n\
- Every safety invariant should have at least one direct executable oracle.\n\
- Every canonical safety invariant should have two independent evidence layers.\n\
- Every simulator checker should have a negative fixture proving it can fail.\n\
- Every client-visible invariant should have an end-to-end workload.\n\
- Every persistence invariant should have failure-injection or crash/reopen coverage.\n\
- Every liveness obligation should state its fairness and timing assumptions.\n\n\
## Layer Legend\n\n\
- D: direct executable oracle.\n\
- E2E: client-visible end-to-end consequence.\n\
- none: not covered, or not the right layer for that predicate.\n\n",
    );
}

fn render_indexes(output: &mut String, registry: &RegistryDocument) {
    output.push_str("## Family Map\n\n");
    render_family_map(output, &registry.invariants);
    output.push_str("\n## List\n\n");
    output.push_str("| ID | One-line description |\n| --- | --- |\n");
    for entry in sorted_invariants(&registry.invariants) {
        let _ = writeln!(output, "| `{}` | {} |", entry.id, entry.statement);
    }

    output.push_str("\n## First Closures\n\n");
    output.push_str(
        "These are the first closures because they turn broad green checks into\n\
named temporal or witness-based verdicts.\n\n\
| ID | Class | Work |\n\
| --- | --- | --- |\n",
    );
    for entry in sorted_invariants(&registry.invariants)
        .into_iter()
        .filter(|entry| entry.priority == "p0")
    {
        let _ = writeln!(
            output,
            "| `{}` | {} | {} |",
            entry.id, entry.action_class, entry.next_action
        );
    }

    output.push_str("\n## Evidence References\n\n");
    render_evidence_references(output, &registry.evidence);
    output.push_str("\n## Normative Clauses\n\n");
    output.push_str("| Clause | Parent | Normative statement |\n| --- | --- | --- |\n");
    for clause in &registry.clauses {
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} |",
            clause.id, clause.invariant_id, clause.statement
        );
    }
}

fn render_catalog(output: &mut String, registry: &RegistryDocument) {
    output.push_str("\n## Catalog\n\n");
    for (family, label, _) in FAMILY_ORDER {
        let _ = writeln!(output, "### {label}\n");
        for entry in sorted_invariants(&registry.invariants)
            .into_iter()
            .filter(|entry| entry.family == *family)
        {
            let _ = writeln!(output, "#### `{}` {}\n", entry.id, entry.title);
            let _ = writeln!(
                output,
                "Kind: {}. Tier: {}.\n",
                kind_label(&entry.kind),
                entry.tier
            );
            let _ = writeln!(output, "Statement: {}\n", entry.statement);
            let _ = writeln!(output, "Scope: {}\n", entry.scope);
            let _ = writeln!(output, "Assumptions: {}\n", entry.assumptions);
            output.push_str("Required clauses:\n");
            for clause in registry
                .clauses
                .iter()
                .filter(|clause| clause.invariant_id == entry.id)
            {
                let _ = writeln!(output, "- `{}`: {}", clause.id, clause.statement);
            }
            output.push_str("\nEvidence now:\n");
            for (label, layer) in [
                ("TLA+", "tla"),
                ("Simulator", "simulator"),
                ("Tests", "tests"),
                ("Maelstrom", "maelstrom"),
            ] {
                let _ = writeln!(
                    output,
                    "- {label}: {}",
                    entry.current_coverage.get(layer).map_or("", String::as_str)
                );
            }
            let _ = writeln!(
                output,
                "\nNext ({}): {}\n",
                entry.action_class, entry.next_action
            );
        }
    }
}

fn render_count_table(output: &mut String, counts: &RegistryCounts) {
    output.push_str("| Scope | Count |\n| --- | ---: |\n");
    for (label, count) in [
        (
            "Canonical Raft paper safety properties",
            counts.canonical_raft_safety_properties,
        ),
        (
            "Predicates in Rafter's current TLA+ config",
            counts.tla_predicates_now,
        ),
        (
            "Well-formedness meta-invariants",
            counts.well_formedness_meta_invariants,
        ),
        (
            "Semantic safety invariants",
            counts.semantic_safety_invariants,
        ),
        ("Liveness obligations", counts.liveness_obligations),
        ("Catalog entries", counts.total_entries),
    ] {
        let _ = writeln!(output, "| {label} | {count} |");
    }
}

fn render_family_map(output: &mut String, invariants: &[RegistryInvariant]) {
    let counts = count_by(invariants.iter().map(|entry| entry.family.as_str()));
    output.push_str("| Family | Entries | Purpose |\n| --- | ---: | --- |\n");
    for (family, label, purpose) in FAMILY_ORDER {
        let _ = writeln!(
            output,
            "| {label} | {} | {purpose} |",
            counts.get(family).copied().unwrap_or_default()
        );
    }
}

fn render_evidence_references(output: &mut String, evidence: &[RegistryEvidence]) {
    output.push_str(
        "| ID | Clauses | Layer | Strength | Reference |\n\
| --- | --- | --- | --- | --- |\n",
    );
    let mut sorted = evidence.iter().collect::<Vec<_>>();
    sorted.sort_by_key(|record| {
        let (prefix, number) = split_id(&record.id);
        (
            PREFIX_ORDER
                .iter()
                .position(|candidate| *candidate == prefix)
                .unwrap_or(usize::MAX),
            number,
            record.layer.as_str(),
            record.strength.as_str(),
            record.path.as_str(),
        )
    });
    for record in sorted {
        let mut reference = format!("`{}#{}`", record.path, record.symbol);
        if let Some(fixture) = &record.negative_fixture {
            let _ = write!(reference, "; negative fixture `{fixture}`");
        }
        if let Some(group) = &record.atomic_group {
            let _ = write!(reference, "; reviewed atomic group `{group}`");
        }
        if let Some(exemption) = &record.negative_fixture_exemption {
            let _ = write!(reference, "; negative fixture exemption `{exemption}`");
        }
        let _ = writeln!(
            output,
            "| `{}` | `{}` | {} | {} | {} |",
            record.id,
            record.clauses.join(","),
            record.layer,
            record.strength,
            reference
        );
    }
}

fn sorted_invariants(invariants: &[RegistryInvariant]) -> Vec<&RegistryInvariant> {
    let mut sorted = invariants.iter().collect::<Vec<_>>();
    sorted.sort_by_key(|entry| {
        let (prefix, number) = split_id(&entry.id);
        (
            PREFIX_ORDER
                .iter()
                .position(|candidate| *candidate == prefix)
                .unwrap_or(usize::MAX),
            number,
        )
    });
    sorted
}

fn split_id(id: &str) -> (&str, usize) {
    let (prefix, number) = id.split_once('-').unwrap_or((id, "0"));
    (prefix, number.parse().unwrap_or(usize::MAX))
}

fn kind_label(kind: &str) -> &str {
    match kind {
        "well_formedness" => "well-formedness",
        "safety" => "safety",
        "liveness" => "liveness",
        other => other,
    }
}

fn count_by<'a>(values: impl Iterator<Item = &'a str>) -> BTreeMap<&'a str, usize> {
    let mut counts = BTreeMap::new();
    for value in values {
        *counts.entry(value).or_default() += 1;
    }
    counts
}

#[cfg(test)]
mod tests {
    use std::{fs, path::PathBuf};

    use super::render_registry_markdown;
    use crate::RegistryDocument;

    #[test]
    fn checked_in_document_matches_the_canonical_renderer() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let registry = RegistryDocument::load(&root.join("verification/raft-invariants.yaml"))
            .expect("parse registry");
        let checked_in = fs::read_to_string(root.join("docs/raft-invariants.md"))
            .expect("read rendered document");

        assert_eq!(checked_in, render_registry_markdown(&registry));
    }

    #[test]
    fn rendering_is_deterministic() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let registry = RegistryDocument::load(&root.join("verification/raft-invariants.yaml"))
            .expect("parse registry");

        assert_eq!(
            render_registry_markdown(&registry),
            render_registry_markdown(&registry)
        );
    }
}
